namespace: hello-world
type: NodePort
service:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP # default TCP
ingress:
  paths:
    - path: "/api"
      jwtValidate: true # default false
      stripPath: true  # default false
      service:
#       name: "srv-name" # default $.Release.Name
        port:
          number: 8080
